### ISSUE TITLE
checkConditionExpectedsAndActuals is wrong

### ISSUE THREAD

**Issue by sgrillon14** [NoraUi/NoraUi#134]
the actual value and expected value comparator is wrong

```
  private Predicate<GherkinConditionedLoopedStep> checkConditionExpectedsAndActuals() {
        return p -> {
            boolean equalSizes = p.getActual().split(";").length == p.getExpected().split(";").length;
            if (!equalSizes) {
                log.error(Messages.getMessage(TechnicalException.TECHNICAL_EXPECTED_ACTUAL_SIZE_DIFFERENT));
            }
            return equalSizes;
        };
    }
```

## Your Environment

* Robot generated by NoraUi Version: V4.0.0.0
* NoraUi Version used: V4.1.6
* Operating System and version: Unix and Windows
* Data input provider: Excel
* Data output provider: Excel
* Browser and version: Chrome 80
* WebDriver and version: ChromeDriver 80
* Link to your project: http://

**Comment by ArKniiD** [comment]
Le test est bien correct. On vient tester les tailles pour savoir si les conditions appliquées à un step sont bien construites. Si le nombre d'expected est différent du nombre d'actual, ça ne sert à rien d'aller plus loin car cela veut dire qu'il y a une mauvaise écriture du step au niveau de Gherkin
