### ISSUE TITLE
NoraUI is unable to quit WebDriver before running new scenario

### ISSUE THREAD

**Issue by guillaume-moirod** [NoraUi/NoraUi#142]
## Describe the bug

Need to start a fresh new browser for each sequential scenario.
So i implemented a step to call com.github.noraui.utils.Context.quit().
But com.github.noraui.browser.waits.Wait does not allow that :
- it is static
- it initializes a wrapper of first WebDriver created
- it is incapable to define new wrapper for new Webdriver

## Steps to reproduce

1. Call 2 scenarios A and B with same tag 'tag'
2. At end of A or begining of B, implement a Step wich does com.github.noraui.utils.Context.quit().
3. In scenario B, implement a step which waits for an element. 
4. Run with tag 'tag'

## Expected Behavior

The 2 scenarios are successful

## Current Behavior

org.openqa.selenium.NoSuchSessionException: Session ID is null. Using WebDriver after calling quit()?

## Possible Solution

com.github.noraui.browser.waits.Wait is not stateless. So do not use static attributes.

## Context & Motivation

Chain scenarios without interferences : https://www.selenium.dev/documentation/en/guidelines_and_recommendations/fresh_browser_per_test/

## Your Environment

* NoraUi Version used: V4.3.0
* Operating System and version: N/A
* Data input provider: N/A
* Data output provider: N/A
* Browser and version: N/A
* WebDriver and version: N/A

**Comment by sgrillon14** [comment]
Please reopen this issue if the problem occurs in a version higher than 4.4.0
