### ISSUE TITLE
Give possibility to add custom arguments to browser

### ISSUE THREAD

**Issue by guillaume-moirod** [NoraUi/NoraUi#143]
Run NoraUI in a Kubernetes Gitlab CI runner :

Problem : Docker images with chrome define too small /dev/shm fs (https://github.com/elgalu/docker-selenium/issues/20)

3 ways to mitigate : 
- Map /dev/shm form host : not possible in this context
- Increase /dev/shm : not sure it is possible in Dockerfile
- use Chrome flag "--disable-dev-shm-usage" to use /tmp instead

So the easiest solution is to disable /dev/shm but we need to be able to pass extra arguments to the browser.
This is actually not the case.

## Possible Solution

Add a property that will be passed during com.github.noraui.browser.DriverFactory.generateXXXXXXDriver()

## Context & Motivation

Be able to run in modern infrastructures.

**Comment by sgrillon14** [comment]
**1st solution:**
fix your problem in a Dockerfile.

**2nd solution:**
do not use Docker for Chrome. In your gitlab-ci.yml add this:

```
  before_script:
    ##################################################
    # Install Latest Google chrome package on system #
    ##################################################
    - curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
    - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
    - apt-get -y update
    - apt-get -y install google-chrome-stable
```

**3th solution:**
Wait NoraUi V4.4.0 and use `disable-dev-shm-usage` in `xxxxxxxx-robot\src\main\resources\webdrivers.properties`

**Comment by guillaume-moirod** [comment]
1. Not sure we can resize /dev/shm in a Dockerfile. There is a dedicated option for containers (--shm-size) for this.
2. In my context i use runners in Kubernetes, hence it runs in pods, so containers => It has to run in a container. FYI i use markhobson/maven-chrome image
3. That's what i did in v4.3.0. But i had to redefine com.github.noraui.browser.DriverFactory in my own code.

**Comment by sgrillon14** [comment]
/!\ IMPORTANT migration 4.3.x to 4.4.x !!!  https://noraui.github.io/migrate.md

**Comment by sgrillon14** [comment]
Please reopen this issue if the problem occurs in a version higher than 4.4.0
