### ISSUE TITLE
Driver not renewed when browser crashes

### ISSUE THREAD

**Issue by gmoirod** [NoraUi/NoraUi#145]
## Describe the bug

Sometimes the browser crashes. A lot if running in a container (see #143 )
When it arrives, the driver is not correctly cleaned and it is reused in following scenarios, giving a "org.openqa.selenium.NoSuchSessionException: invalid session id" error.

## Expected Behavior

Driver is recreated from scratch.

## Current Behavior

Driver is reused.

## Possible Solution

Catch NoSuchSessionException in StepInterceptor and quit properly existing drivers.

## Your Environment

* Robot generated by NoraUi Version: N/A
* NoraUi Version used: V4.3.0
* Operating System and version: N/A
* Data input provider: N/A
* Data output provider: N/A
* Browser and version: Chrome 83
* WebDriver and version: ChromeDriver 83

**Comment by sgrillon14** [comment]
Please reopen this issue if the problem occurs in a version higher than 4.4.0
