### ISSUE TITLE
Counter Error in EXPECTED_RESULTS_X when value is zero

### ISSUE THREAD

**Issue by JarekLipsko** [NoraUi/NoraUi#20]
[Excel] > <EXPECTED_RESULTS_1>4 Scenarios (0 failed, 4 passed)</EXPECTED_RESULTS_1>
[Excel] > <EXPECTED_RESULTS_2>36 Steps (0 failed, 0 skipped, 36 passed)</EXPECTED_RESULTS_2>

...

4 Scenarios (4 passed)
36 Steps (36 passed)

**Comment by ArKniiD** [comment]
Hello @JarekLipsko 

I don't really get what problem you are facing. ?
Can you provide more explanations please ?

**Comment by sgrillon14** [comment]
fixed on PR#21
