### ISSUE TITLE
bug on "I clean download directory." generic step

### ISSUE THREAD

**Issue by JarekLipsko** [NoraUi/NoraUi#30]
OK on my `Windows 7 + Eclipse` env but I have this bug on `Unix + Jenkins`:

![2018-01-04_104351](https://user-images.githubusercontent.com/32483833/34557953-56505b3c-f13c-11e7-8916-33208b414d45.png)

**Comment by sgrillon14** [comment]
2 user case:

1) You test an application and you clean `downloadFiles` each execution with `I clean download directory.`   => Problem solve in next version (3.0.2 or more) => This evolution in NoraUi create `downloadFiles` folder if not exist.

2) You need keep all download files after all execution => You need remove this line in .gitignore file and commit/push `downloadFiles` folder:  `downloadFiles/`
