### ISSUE TITLE
Generic step (I expect to have 'xxx.xxx-xxx' with the text 'xxx'.) do not work on multi-line mode

### ISSUE THREAD

**Issue by JarekLipsko** [NoraUi/NoraUi#36]
Gherkin file:
`And I expect to have 'cellularseller.CellularsellerPage-error_message' with the text 'line1line2line3'.`

My Web element is:
`<div _ngcontent-c1="" class="alert alert-danger" id="divErrMsg" role="alert">line1<br>line2<br>line3</div>`

this step do not find the sentance if text contain more one line.

**Comment by ArKniiD** [comment]
Fix commited (ee35a06) + review OK
