### ISSUE TITLE
checkMandatoryFieldTextTypeTest unit test fail

### ISSUE THREAD

**Issue by sgrillon14** [NoraUi/NoraUi#41]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.027 s <<< FAILURE! - in com.github.noraui.application.steps.CommonStepsUT
[ERROR] checkMandatoryFieldTextTypeTest(com.github.noraui.application.steps.CommonStepsUT)  Time elapsed: 1.604 s  <<< ERROR!
java.lang.NullPointerException
	at com.github.noraui.application.steps.CommonStepsUT.checkMandatoryFieldTextTypeTest(CommonStepsUT.java:61)

**Comment by ArKniiD** [comment]
Fixed by PR (fixe issue #41)
