### ISSUE TITLE
Translation fail in optional part

### ISSUE THREAD

**Issue by sgrillon14** [NoraUi/NoraUi#5]
When I run all unit tests on "hello" scenario with French lang, I have this message in logs console:

java.lang.AssertionError: Échec : /!\ Accès à l'action « no exist element » dans demo. /!\ [**Expected condition failed: waiting for element to be clickable**: By.xpath: .//*[@id='fake'] (tried for 3 second(s) with 500 MILLISECONDS interval)]

**Comment by ArKniiD** [comment]
Hi @sgrillon14,
This mistranslation is not an issue. The message between [] is the error details provided by selenium web drivers. We cannot change this message

**Comment by sgrillon14** [comment]
OK
