### ISSUE TITLE
Data provider DB (MYSQL) is KO in CI

### ISSUE THREAD

**Issue by sgrillon14** [NoraUi/NoraUi#6]
[2017-09-24 20:27:45]: /!\ Data provider used is DB (MYSQL). /!\
[2017-09-24 20:27:46]: java.lang.NullPointerException
[2017-09-24 20:27:46]: Scenario: hello => step: 67 and cases: 0 -->  runs: 0, failures: 0, errors: 0 and skips: 0
[2017-09-24 20:27:46]: [DbMySql] > <EXPECTED_RESULTS>Tests run: 0, Failures: 0, Errors: 0, Skipped: 0</EXPECTED_RESULTS>

**Comment by sgrillon14** [comment]
Nico, I add `resultColumnName = ResultColumnNames.getAuthorizedNames().get(0);` in `initColumns()` but can you add an other mlodification with i18n ?

**Comment by ArKniiD** [comment]
Which modification?

**Comment by sgrillon14** [comment]
My modification take always the first result key word ("Résultat"). So, 2 solutions:
- take local (replace List `ResultColumnNames.getAuthorizedNames()` by a Map ("fr", "Résultat" and "en", "result") and use get element by key (with local variable).
- just switch "result" and "Résultat" and use always "result" (always "en" by default in SQL).

what do you think about it?

**Comment by ArKniiD** [comment]
Hello Stéphane,

You can see the above commit (04ec53c) on which I proposed a solution.

**Comment by sgrillon14** [comment]
Yes, approved :)

**Comment by ArKniiD** [comment]
I fixed column names in sql files for CI in this commit 0c7edbf .
Everything is OK.
I close this bug ;)
