### ISSUE TITLE
Feature file 

### ISSUE THREAD

**Issue by nipdoni** [NoraUi/NoraUi#69]
Hello,

Can we make a call between features ?, For example a feature calls another feature to execute a specific scenario without rewriting it.
What i want to do exactly is to create a feature only for the connection and call it by other feature.

**Comment by ArKniiD** [comment]
Hello,

Natively gherkin does not allow this kind of feature. There is no way for the moment to tell gherkin to include another external gherkin feature. 
This could developed in the next version of Noraui but it is not the most prioritized thing we identify by now as each Gherkin file must describe a unique and independent scenario.

Regards
Nicolas

**Comment by nipdoni** [comment]
Thank you for your answer.

And if i create a new class step and a new class Page, is it possible to do authentication in new class and another test in another class, with a different feature ? , like that i will have for example 2 class Step, and 2 class Page, or i should change others parameters ?

**Comment by sgrillon14** [comment]
NoraUi use any best practice of Gherkin/Cucumber/Selenium. If you want manage login and logout, see LoginLogout.feature in NoraUi academy. Is it a sample on JHipster application.
