### ISSUE TITLE
function passOver possibilities

### ISSUE THREAD

**Issue by sgrillon14** [NoraUi/NoraUi#7]
[stackoverflow #45618027](https://stackoverflow.com/questions/45618027/function-passover-possibilities)

I'm working on autotest with noraui.

I would like to open a subdropdown (button => click => dropdown => passOver => subdropdown). This subdropdown can only appear with a passOver, if we click on the dropdownmenu, nothing happen.

![vjltq](https://user-images.githubusercontent.com/5530550/30971897-91785234-a469-11e7-9831-00270b333b5c.png)

But my passOver function doesn't work

protected void passOver(PageElement element) throws TechnicalException, FailureException {

    try {
        String javascript = "var evObj = document.createEvent('MouseEvents');" + "evObj.initMouseEvent(\"mouseover\",true, false, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null);"
                + "arguments[0].dispatchEvent(evObj);";
        ((JavascriptExecutor) getDriver()).executeScript(javascript, Context.waitUntil(ExpectedConditions.presenceOfElementLocated(Utilities.getLocator(element))));
    } catch (Exception e) {
        new Result.Failure<>(e.getMessage(), Messages.format(Messages.FAIL_MESSAGE_UNABLE_TO_PASS_OVER_ELEMENT, element, element.getPage().getApplication()), true,
                element.getPage().getCallBack());
    }

}
The steps code

@When("I pass over on '(.*)-(.*)'")
public void passOver(String page, String toPassOver) throws TechnicalException, FailureException {

  loggerStep.debug(page + " passOver: " + toPassOver);
  passOver(Page.getInstance(page).getPageElementByKey('-' + toPassOver)); }
I'm looking for passOver works like a mouse hovering the dropdownmenu ("Mise à jour").

**Comment by sgrillon14** [comment]
can you extract your DOM in a sample please?

You can add this sample in this repository: https://github.com/NoraUi/noraui.github.io/tree/master/demo

**Comment by ArKniiD** [comment]
Hello @sgrillon14 

Have you tried the following scenario ?

- click a first time on the dropdown menu with clickOn() method
- then trig a passOver event with passOver() method
- then wait for subdropdown to be visible
- and finally trig a second passOver event with passOver() method

Regards

**Comment by sgrillon14** [comment]
if no reproduced by alexis ouvrard (https://stackoverflow.com/questions/45618027/function-passover-possibilities), we close in V3.x.x

**Comment by ArKniiD** [comment]
I can do a last try on a small twitter bootstrap app example. After that, we'll define wether this behavior is a bug to fix or a new feature to add in the next version.

Regards

**Comment by ArKniiD** [comment]
Fixed by commit 5fcab5d
