### ISSUE TITLE
Data provider

### ISSUE THREAD

**Issue by nipdoni** [NoraUi/NoraUi#75]
Hello,

I have a problem with the data providers, i tried to change the type of data to provide and i put this:

#type of input dataProvider (EXCEL, CSV, DB, REST, GHERKIN, noraui.data.xxx.YourCustomInputDataProvider)
dataProvider.in.type=GHERKIN
#type of output dataProvider (EXCEL, CSV, REST, CONSOLE, noraui.data.xxx.YourCustomOutputDataProvider)
dataProvider.out.type=CONSOLE
 
But i have always this problem : 

 [2018-05-21 13:39:58]: CW_COL_SAI_T01_AC NOT set!
[2018-05-21 13:39:58]: java.nio.file.NoSuchFileException: src\test\resourcesnullCW_COL_SAI_T01_AC.feature
[2018-05-21 13:39:58]: Wrong data file (IOException, EmptyDataFileContentException or WrongDataFileFormatException)
noraui.exception.data.EmptyDataFileContentException: Input data file is empty or only result column is provided.
	at noraui.data.gherkin.InputGherkinDataProvider.initColumns(InputGherkinDataProvider.java:108)
	at noraui.data.gherkin.InputGherkinDataProvider.prepare(InputGherkinDataProvider.java:35)
	at noraui.indus.MavenRunCounter.countNbCasFailuresAndSkipped(MavenRunCounter.java:198)
	at noraui.indus.MavenRunCounter.countNbCasFailuresAndSkipped(MavenRunCounter.java:83)
	at noraui.indus.MavenRunCounter.count(MavenRunCounter.java:58)

And the Gherkin file is filled with the data:

Scenario Outline:  Scenario that 1st sample.

	Given 'Page_HOME' est ouvert.
	Then Application ouverte avec succès et Demande des informations de connexion.
	
	Given Je vérifie que user '<user>' n'est pas vide.
        Given Je vérifie que password '<password>' n'est pas vide.
        Given Je vérifie que code '<codeClient>' n'est pas vide.
	
	When Entrer les informations de connexion '<codeClient>' '<domaine>' '<user>' '<password>'.
	Then Affichage de l'écran 'Sélectionner un dossier'.

	When Selectionner le dossier '<dossier>'.
	Then Affichage de l'écran d'accueil permettant la navigation au sein du dossier sélectionné.
	And Date de facture champ non-modifiable.
	
			Examples:
	  #DATA
	  	  |id|codeClient|domaine|user|password|dossier|
    |1|test|domaine1|test|test|dossier1|

   	 #END

  
on the other hand when i change the settings and i put:

#type of input dataProvider (EXCEL, CSV, DB, REST, GHERKIN, noraui.data.xxx.YourCustomInputDataProvider)
dataProvider.in.type=EXCEL
#type of output dataProvider (EXCEL, CSV, REST, CONSOLE, noraui.data.xxx.YourCustomOutputDataProvider)
dataProvider.out.type=EXCEL

I will not have problems running, the problem here is that the data used is the data in the Gherkin file and not in Excel file.
And when i try to make a modification on Excel file it does not take account my modification.
The name of the Excel file is the same for the Gherkin file.
I do not know if there are other parameters to change, or if i made a mistake somewhere.

Thank you.

**Comment by sgrillon14** [comment]
have you `CW_COL_SAI_T01_AC=/steps/scenarios/` in `/robot/src/main/resources/scenarios.properties` file?

**Comment by nipdoni** [comment]
Yes i have it, i tested with CW_COL_SAI_T01_AC=/steps/ci/ , too but it does not work.

**Comment by ArKniiD** [comment]
Hello,

Where is your feature file located ?

**Comment by nipdoni** [comment]
My feature file is located in : src/test/resources/steps/ci.

**Comment by sgrillon14** [comment]
**Other subject:** if you use French language: `# language: fr` And all French key word.

Sample: https://github.com/NoraUi/NoraUi/blob/master/src/test/resources/steps/bonjour.feature

**Comment by nipdoni** [comment]
It is resolved, also changing the name of the feature i removed " _ " .
Thank you.
