### ISSUE TITLE
clickOnByJs failed with XPath containing quotes

### ISSUE THREAD

**Issue by JimmyTournemaine** [NoraUi/NoraUi#80]
Using `When I click by js on 'MyPage-MyElement'` from CommonSteps
If the `.ini` files which is referred by the PageElement is containing quotes, the Javascript execution will failed.

For instance, we were trying to use `xpath=//img[@name="imgValider"]`.

We fixed it by chaining `Utilities.getLocatorValue(toClick, args)` to `replace("\"", "\\\"") `

Any chance to fix it in the next version ?

**Comment by sgrillon14** [comment]
The NoraUi team recommends using simple quotes in xpath. if you use the following syntax, does this cause you another problem?

` xpath=//img[@name='imgValider']`

**Comment by JimmyTournemaine** [comment]
No, we try it and it works perfectly fine. However, all of ours XPath are defined with double quotes.

We should use single quotes yet, but I think it's still an issue.

**Comment by sgrillon14** [comment]
An other question of curiosity. Why do you use `clickOnByJs` rather than the classic `clickOn`?
